insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(0,0,20,150,3,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(1,0,20,149,3,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(2,0,20,148,3,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(3,0,20,147,3,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(4,0,20,146,3,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(5,0,20,145,3,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6,0,20,144,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(7,0,20,113,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(8,0,20,76,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(9,0,20,39,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(10,0,19,150,4,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(11,0,19,148,4,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(12,0,19,145,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(13,0,19,140,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(14,0,19,139,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(15,0,19,124,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(16,0,19,99,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(17,0,19,74,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(18,0,19,49,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(19,0,18,150,4,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(20,0,18,149,4,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(21,0,18,148,4,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(22,0,18,144,4,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(23,0,18,139,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(24,0,18,138,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(25,0,18,137,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(26,0,18,136,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(27,0,18,135,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(28,0,18,134,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(29,0,18,133,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(30,0,18,132,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(31,0,18,131,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(32,0,18,130,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(33,0,18,129,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(34,0,18,127,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(35,0,18,104,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(36,0,18,81,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(37,0,18,59,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(38,0,17,150,6,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(39,0,17,149,6,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(40,0,17,148,6,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(41,0,17,145,6,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(42,0,17,139,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(43,0,17,138,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(44,0,17,137,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(45,0,17,136,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(46,0,17,135,5,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(47,0,17,134,5,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(48,0,17,133,5,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(49,0,17,132,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(50,0,17,131,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(51,0,17,130,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(52,0,17,129,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(53,0,17,128,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(54,0,17,127,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(55,0,17,126,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(56,0,17,125,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(57,0,17,124,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(58,0,17,123,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(59,0,17,122,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(60,0,17,121,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(61,0,17,120,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(62,0,17,119,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(63,0,17,107,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(64,0,17,92,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(65,0,17,78,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(66,0,17,64,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(67,0,16,150,7,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(68,0,16,149,7,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(69,0,16,148,7,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(70,0,16,147,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(71,0,16,143,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(72,0,16,138,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(73,0,16,136,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(74,0,16,132,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(75,0,16,131,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(76,0,16,130,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(77,0,16,129,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(78,0,16,122,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(79,0,16,108,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(80,0,16,95,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(81,0,16,81,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(82,0,16,67,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(83,0,16,54,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(84,0,15,150,7,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(85,0,15,149,7,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(86,0,15,148,7,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(87,0,15,147,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(88,0,15,141,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(89,0,15,137,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(90,0,15,134,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(91,0,15,127,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(92,0,15,126,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(93,0,15,125,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(94,0,15,124,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(95,0,15,111,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(96,0,15,98,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(97,0,15,85,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(98,0,15,72,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(99,0,15,59,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(100,0,14,150,10,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(101,0,14,149,10,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(102,0,14,141,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(103,0,14,138,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(104,0,14,132,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(105,0,14,131,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(106,0,14,130,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(107,0,14,129,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(108,0,14,128,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(109,0,14,127,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(110,0,14,126,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(111,0,14,125,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(112,0,14,124,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(113,0,14,123,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(114,0,14,122,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(115,0,14,121,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(116,0,14,120,7,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(117,0,14,119,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(118,0,14,115,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(119,0,14,107,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(120,0,14,98,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(121,0,14,89,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(122,0,14,81,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(123,0,14,72,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(124,0,14,64,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(125,0,13,150,0,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(126,0,13,149,0,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(127,0,13,148,0,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(128,0,13,147,0,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(129,0,13,141,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(130,0,13,134,9,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(131,0,13,133,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(132,0,13,132,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(133,0,13,131,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(134,0,13,130,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(135,0,13,129,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(136,0,13,128,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(137,0,13,127,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(138,0,13,126,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(139,0,13,125,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(140,0,13,124,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(141,0,13,123,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(142,0,13,122,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(143,0,13,121,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(144,0,13,120,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(145,0,13,119,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(146,0,13,118,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(147,0,13,117,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(148,0,13,116,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(149,0,13,115,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(150,0,13,114,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(151,0,13,113,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(152,0,13,112,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(153,0,13,111,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(154,0,13,110,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(155,0,13,109,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(156,0,13,101,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(157,0,13,93,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(158,0,13,85,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(159,0,13,77,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(160,0,13,69,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(161,0,12,150,6,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(162,0,12,147,6,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(163,0,12,144,6,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(164,0,12,136,5,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(165,0,12,135,5,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(166,0,12,126,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(167,0,12,123,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(168,0,12,117,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(169,0,12,116,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(170,0,12,115,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(171,0,12,114,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(172,0,12,109,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(173,0,12,96,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(174,0,12,82,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(175,0,12,69,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(176,0,11,150,8,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(177,0,11,146,8,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(178,0,11,142,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(179,0,11,141,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(180,0,11,132,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(181,0,11,123,5,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(182,0,11,122,5,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(183,0,11,121,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(184,0,11,118,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(185,0,11,117,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(186,0,11,116,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(187,0,11,115,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(188,0,11,114,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(189,0,11,113,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(190,0,11,112,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(191,0,11,111,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(192,0,11,110,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(193,0,11,109,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(194,0,11,105,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(195,0,11,96,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(196,0,11,87,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(197,0,11,79,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(198,0,10,150,12,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(199,0,10,146,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(200,0,10,143,11,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(201,0,10,140,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(202,0,10,137,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(203,0,10,131,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(204,0,10,128,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(205,0,10,124,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(206,0,10,123,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(207,0,10,122,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(208,0,10,121,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(209,0,10,120,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(210,0,10,119,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(211,0,10,118,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(212,0,10,117,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(213,0,10,116,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(214,0,10,115,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(215,0,10,114,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(216,0,10,113,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(217,0,10,112,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(218,0,10,111,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(219,0,10,110,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(220,0,10,109,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(221,0,10,108,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(222,0,10,107,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(223,0,10,106,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(224,0,10,105,5,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(225,0,10,104,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(226,0,10,99,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(227,0,10,93,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(228,0,10,86,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(229,0,10,80,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(230,0,10,74,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(231,0,9,150,12,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(232,0,9,144,11,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(233,0,9,143,11,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(234,0,9,138,10,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(235,0,9,135,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(236,0,9,132,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(237,0,9,127,9,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(238,0,9,126,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(239,0,9,125,8,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(240,0,9,124,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(241,0,9,123,8,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(242,0,9,122,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(243,0,9,121,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(244,0,9,120,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(245,0,9,119,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(246,0,9,118,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(247,0,9,117,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(248,0,9,116,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(249,0,9,115,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(250,0,9,114,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(251,0,9,113,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(252,0,9,112,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(253,0,9,111,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(254,0,9,110,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(255,0,9,109,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(256,0,9,108,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(257,0,9,107,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(258,0,9,106,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(259,0,9,105,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(260,0,9,104,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(261,0,9,103,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(262,0,9,102,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(263,0,9,101,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(264,0,9,100,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(265,0,9,99,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(266,0,9,98,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(267,0,9,97,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(268,0,9,96,3,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(269,0,9,95,3,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(270,0,9,94,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(271,0,9,90,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(272,0,9,84,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(273,0,9,79,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(274,0,8,150,8,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(275,0,8,143,8,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(276,0,8,136,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(277,0,8,134,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(278,0,8,122,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(279,0,8,121,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(280,0,8,120,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(281,0,8,119,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(282,0,8,118,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(283,0,8,117,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(284,0,8,116,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(285,0,8,115,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(286,0,8,114,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(287,0,8,113,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(288,0,8,112,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(289,0,8,111,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(290,0,8,110,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(291,0,8,109,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(292,0,8,108,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(293,0,8,107,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(294,0,8,106,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(295,0,8,105,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(296,0,8,104,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(297,0,8,103,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(298,0,8,102,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(299,0,8,101,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(300,0,8,100,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(301,0,8,99,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(302,0,8,98,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(303,0,8,97,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(304,0,8,96,5,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(305,0,8,95,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(306,0,8,94,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(307,0,8,89,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(308,0,8,74,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(309,0,8,59,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(310,0,7,150,8,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(311,0,7,142,8,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(312,0,7,135,7,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(313,0,7,132,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(314,0,7,126,7,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(315,0,7,125,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(316,0,7,124,7,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(317,0,7,123,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(318,0,7,122,7,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(319,0,7,121,6,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(320,0,7,120,6,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(321,0,7,119,6,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(322,0,7,118,6,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(323,0,7,117,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(324,0,7,116,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(325,0,7,115,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(326,0,7,114,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(327,0,7,113,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(328,0,7,112,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(329,0,7,111,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(330,0,7,110,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(331,0,7,109,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(332,0,7,108,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(333,0,7,107,5,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(334,0,7,106,5,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(335,0,7,105,5,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(336,0,7,104,5,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(337,0,7,103,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(338,0,7,102,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(339,0,7,101,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(340,0,7,100,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(341,0,7,99,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(342,0,7,98,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(343,0,7,97,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(344,0,7,96,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(345,0,7,95,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(346,0,7,94,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(347,0,7,93,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(348,0,7,92,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(349,0,7,91,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(350,0,7,90,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(351,0,7,89,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(352,0,7,78,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(353,0,7,64,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(354,0,6,150,13,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(355,0,6,142,6,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(356,0,6,141,6,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(357,0,6,135,11,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(358,0,6,131,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(359,0,6,130,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(360,0,6,129,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(361,0,6,128,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(362,0,6,127,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(363,0,6,126,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(364,0,6,125,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(365,0,6,124,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(366,0,6,123,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(367,0,6,122,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(368,0,6,121,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(369,0,6,120,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(370,0,6,119,9,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(371,0,6,118,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(372,0,6,117,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(373,0,6,116,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(374,0,6,115,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(375,0,6,114,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(376,0,6,113,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(377,0,6,112,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(378,0,6,111,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(379,0,6,110,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(380,0,6,109,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(381,0,6,108,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(382,0,6,107,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(383,0,6,106,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(384,0,6,105,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(385,0,6,104,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(386,0,6,103,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(387,0,6,102,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(388,0,6,101,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(389,0,6,100,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(390,0,6,99,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(391,0,6,98,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(392,0,6,97,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(393,0,6,96,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(394,0,6,95,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(395,0,6,94,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(396,0,6,93,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(397,0,6,92,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(398,0,6,91,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(399,0,6,90,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(400,0,6,89,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(401,0,6,88,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(402,0,6,87,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(403,0,6,86,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(404,0,6,85,5,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(405,0,6,84,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(406,0,6,83,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(407,0,6,76,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(408,0,6,69,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(409,0,5,150,16,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(410,0,5,144,15,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(411,0,5,143,15,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(412,0,5,142,15,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(413,0,5,141,15,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(414,0,5,140,15,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(415,0,5,139,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(416,0,5,138,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(417,0,5,137,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(418,0,5,136,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(419,0,5,135,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(420,0,5,134,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(421,0,5,133,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(422,0,5,132,13,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(423,0,5,131,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(424,0,5,130,13,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(425,0,5,129,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(426,0,5,128,12,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(427,0,5,127,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(428,0,5,126,12,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(429,0,5,125,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(430,0,5,124,12,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(431,0,5,123,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(432,0,5,122,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(433,0,5,121,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(434,0,5,120,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(435,0,5,119,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(436,0,5,118,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(437,0,5,117,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(438,0,5,116,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(439,0,5,115,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(440,0,5,114,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(441,0,5,113,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(442,0,5,112,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(443,0,5,111,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(444,0,5,110,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(445,0,5,109,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(446,0,5,108,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(447,0,5,107,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(448,0,5,106,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(449,0,5,105,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(450,0,5,104,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(451,0,5,103,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(452,0,5,102,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(453,0,5,101,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(454,0,5,100,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(455,0,5,99,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(456,0,5,98,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(457,0,5,97,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(458,0,5,96,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(459,0,5,95,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(460,0,5,94,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(461,0,5,93,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(462,0,5,92,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(463,0,5,91,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(464,0,5,90,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(465,0,5,89,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(466,0,5,88,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(467,0,5,87,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(468,0,5,86,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(469,0,5,85,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(470,0,5,84,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(471,0,5,83,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(472,0,5,82,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(473,0,5,81,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(474,0,5,80,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(475,0,5,79,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(476,0,5,74,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(477,0,4,150,10,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(478,0,4,142,9,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(479,0,4,135,8,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(480,0,4,134,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(481,0,4,128,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(482,0,4,124,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(483,0,4,123,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(484,0,4,122,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(485,0,4,121,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(486,0,4,120,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(487,0,4,119,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(488,0,4,118,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(489,0,4,117,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(490,0,4,116,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(491,0,4,115,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(492,0,4,114,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(493,0,4,113,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(494,0,4,112,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(495,0,4,111,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(496,0,4,110,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(497,0,4,109,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(498,0,4,108,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(499,0,4,107,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(500,0,4,106,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(501,0,4,105,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(502,0,4,104,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(503,0,4,98,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(504,0,4,91,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(505,0,4,84,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(506,0,3,150,13,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(507,0,3,143,12,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(508,0,3,139,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(509,0,3,136,11,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(510,0,3,132,11,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(511,0,3,131,11,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(512,0,3,130,11,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(513,0,3,129,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(514,0,3,128,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(515,0,3,127,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(516,0,3,126,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(517,0,3,125,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(518,0,3,124,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(519,0,3,123,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(520,0,3,122,9,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(521,0,3,121,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(522,0,3,120,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(523,0,3,119,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(524,0,3,118,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(525,0,3,117,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(526,0,3,116,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(527,0,3,115,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(528,0,3,114,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(529,0,3,113,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(530,0,3,112,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(531,0,3,111,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(532,0,3,110,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(533,0,3,109,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(534,0,3,108,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(535,0,3,107,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(536,0,3,106,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(537,0,3,105,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(538,0,3,104,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(539,0,3,103,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(540,0,3,102,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(541,0,3,101,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(542,0,3,100,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(543,0,3,99,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(544,0,3,95,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(545,0,3,89,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(546,0,2,150,16,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(547,0,2,142,15,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(548,0,2,137,15,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(549,0,2,136,15,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(550,0,2,135,14,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(551,0,2,134,14,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(552,0,2,133,14,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(553,0,2,132,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(554,0,2,131,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(555,0,2,130,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(556,0,2,129,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(557,0,2,128,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(558,0,2,127,13,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(559,0,2,126,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(560,0,2,125,13,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(561,0,2,124,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(562,0,2,123,13,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(563,0,2,122,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(564,0,2,121,12,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(565,0,2,120,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(566,0,2,119,12,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(567,0,2,118,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(568,0,2,117,12,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(569,0,2,116,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(570,0,2,115,12,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(571,0,2,114,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(572,0,2,113,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(573,0,2,112,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(574,0,2,111,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(575,0,2,110,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(576,0,2,109,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(577,0,2,108,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(578,0,2,107,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(579,0,2,106,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(580,0,2,105,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(581,0,2,104,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(582,0,2,103,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(583,0,2,102,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(584,0,2,101,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(585,0,2,100,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(586,0,2,99,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(587,0,2,98,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(588,0,2,97,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(589,0,2,96,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(590,0,2,95,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(591,0,2,94,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(592,0,2,93,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(593,0,2,92,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(594,0,2,91,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(595,0,2,90,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(596,0,2,89,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(597,0,2,88,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(598,0,2,87,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(599,0,2,86,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(600,0,2,85,7,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(601,0,2,84,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(602,0,2,79,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(603,0,1,150,18,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(604,0,1,149,18,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(605,0,1,148,18,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(606,0,1,147,18,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(607,0,1,146,18,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(608,0,1,145,18,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(609,0,1,144,17,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(610,0,1,143,17,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(611,0,1,142,17,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(612,0,1,141,17,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(613,0,1,140,17,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(614,0,1,139,16,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(615,0,1,138,16,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(616,0,1,137,16,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(617,0,1,136,16,'E',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(618,0,1,135,16,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(619,0,1,134,15,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(620,0,1,133,15,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(621,0,1,132,15,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(622,0,1,131,15,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(623,0,1,130,15,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(624,0,1,129,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(625,0,1,128,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(626,0,1,127,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(627,0,1,126,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(628,0,1,125,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(629,0,1,124,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(630,0,1,123,13,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(631,0,1,122,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(632,0,1,121,13,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(633,0,1,120,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(634,0,1,119,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(635,0,1,118,12,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(636,0,1,117,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(637,0,1,116,12,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(638,0,1,115,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(639,0,1,114,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(640,0,1,113,11,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(641,0,1,112,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(642,0,1,111,11,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(643,0,1,110,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(644,0,1,109,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(645,0,1,108,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(646,0,1,107,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(647,0,1,106,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(648,0,1,105,10,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(649,0,1,104,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(650,0,1,103,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(651,0,1,102,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(652,0,1,101,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(653,0,1,100,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(654,0,1,99,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(655,0,1,98,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(656,0,1,97,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(657,0,1,96,8,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(658,0,1,95,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(659,0,1,94,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(660,0,1,89,0);
