insert into weapon(id, name, fumble, weapon_group) values(0, 'Dagger', 1, 'ONE_HANDED_SLASHING');
insert into weapon(id, name, fumble, weapon_group) values(1, 'Falchion', 5, 'ONE_HANDED_SLASHING');
insert into weapon(id, name, fumble, weapon_group) values(2, 'Hand axe', 4, 'ONE_HANDED_SLASHING');
insert into weapon(id, name, fumble, weapon_group) values(3, 'Maine Gauche', 2, 'ONE_HANDED_SLASHING');
insert into weapon(id, name, fumble, weapon_group) values(4, 'Scimitar', 4, 'ONE_HANDED_SLASHING');
insert into weapon(id, name, fumble, weapon_group) values(5, 'Rapier', 4, 'ONE_HANDED_SLASHING');
insert into weapon(id, name, fumble, weapon_group) values(6, 'Broadsword', 3, 'ONE_HANDED_SLASHING');
insert into weapon(id, name, fumble, weapon_group) values(7, 'Short Sword', 2, 'ONE_HANDED_SLASHING');
insert into weapon(id, name, fumble, weapon_group) values(8, 'Armored fist', 1, 'ONE_HANDED_CONCUSSION');
insert into weapon(id, name, fumble, weapon_group) values(9, 'Club', 4, 'ONE_HANDED_CONCUSSION');
insert into weapon(id, name, fumble, weapon_group) values(10, 'War Hammer', 4, 'ONE_HANDED_CONCUSSION');
insert into weapon(id, name, fumble, weapon_group) values(11, 'Mace', 2, 'ONE_HANDED_CONCUSSION');
insert into weapon(id, name, fumble, weapon_group) values(12, 'Morning star', 8, 'ONE_HANDED_CONCUSSION');
insert into weapon(id, name, fumble, weapon_group) values(13, 'Whip', 6, 'ONE_HANDED_CONCUSSION');
insert into weapon(id, name, fumble, weapon_group) values(14, 'Bola', 7, 'MISSILE');
insert into weapon(id, name, fumble, weapon_group) values(15, 'Composite bow', 4, 'MISSILE');
insert into weapon(id, name, fumble, weapon_group) values(16, 'Heavy crossbow', 5, 'MISSILE');
insert into weapon(id, name, fumble, weapon_group) values(17, 'Light crossbow', 5, 'MISSILE');
insert into weapon(id, name, fumble, weapon_group) values(18, 'Long bow', 5, 'MISSILE');
insert into weapon(id, name, fumble, weapon_group) values(19, 'Short bow', 4, 'MISSILE');
insert into weapon(id, name, fumble, weapon_group) values(20, 'Sling', 6, 'MISSILE');
insert into weapon(id, name, fumble, weapon_group) values(21, 'Battle axe', 5, 'TWO_HANDED');
insert into weapon(id, name, fumble, weapon_group) values(22, 'Flail', 8, 'TWO_HANDED');
insert into weapon(id, name, fumble, weapon_group) values(23, 'War mattock', 6, 'TWO_HANDED');
insert into weapon(id, name, fumble, weapon_group) values(24, 'Quarterstaff', 3, 'TWO_HANDED');
insert into weapon(id, name, fumble, weapon_group) values(25, 'Two-handed sword', 5, 'TWO_HANDED');
insert into weapon(id, name, fumble, weapon_group) values(26, 'Javelin', 4, 'POLE_ARM');
insert into weapon(id, name, fumble, weapon_group) values(27, 'Lance', 7, 'POLE_ARM');
insert into weapon(id, name, fumble, weapon_group) values(28, 'Pole arm', 7, 'POLE_ARM');
insert into weapon(id, name, fumble, weapon_group) values(29, 'Spear', 5, 'POLE_ARM');

insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(1, -10, 1, 10, 0);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(2, -20, 11, 25, 0);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(3, -30, 26, 50, 0);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(4, -15, 1, 10, 2);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(5, -30, 11, 25, 2);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(6, -45, 26, 50, 2);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(7, -90, 51, 100, 2);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(8, -15, 1, 10, 3);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(9, -30, 1, 10, 7);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(10, -40, 1, 10, 9);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(11, -20, 1, 10, 10);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(12, -40, 11, 25, 10);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(13, -60, 26, 50, 10);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(14, -35, 1, 10, 11);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(15, 0, 1, 50, 14);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(16, -20, 51, 100, 14);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(17, -40, 101, 150, 14);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(18, 25, 1, 10, 15);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(19, 0, 11, 100, 15);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(20, -35, 101, 200, 15);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(21, -60, 201, 300, 15);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(22, 30, 1, 20, 16);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(23, 0, 21, 100, 16);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(24, -25, 101, 200, 16);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(25, -40, 201, 300, 16);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(26, -55, 301, 360, 16);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(27, 15, 1, 10, 17);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(28, 0, 11, 100, 17);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(29, -35, 101, 200, 17);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(30, -50, 201, 300, 17);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(31, -75, 301, 360, 17);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(32, 20, 1, 10, 18);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(33, 0, 11, 100, 18);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(34, -30, 101, 200, 18);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(35, -40, 201, 300, 18);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(36, -50, 301, 400, 18);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(37, 10, 1, 10, 19);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(38, 0, 11, 100, 19);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(39, -40, 101, 180, 19);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(40, -70, 181, 240, 19);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(41, 15, 1, 10, 20);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(42, 0, 11, 60, 20);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(43, -40, 61, 120, 20);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(44, -65, 121, 180, 20);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(45, -10, 1, 10, 29);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(46, -20, 11, 25, 29);
insert into weapon_range(id, obModifier, from_distance, to_distance, weapon_fk) values(47, -30, 26, 50, 29);
