insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6000,3,20,150,4,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6001,3,20,149,4,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6002,3,20,148,4,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6003,3,20,145,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6004,3,20,140,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6005,3,20,139,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6006,3,20,121,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6007,3,20,92,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6008,3,20,63,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6009,3,20,35,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6010,3,19,150,6,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6011,3,19,147,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6012,3,19,143,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6013,3,19,135,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6014,3,19,134,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6015,3,19,132,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6016,3,19,115,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6017,3,19,97,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6018,3,19,80,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6019,3,19,62,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6020,3,19,45,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6021,3,18,150,8,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6022,3,18,149,8,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6023,3,18,148,8,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6024,3,18,147,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6025,3,18,142,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6026,3,18,138,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6027,3,18,135,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6028,3,18,127,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6029,3,18,126,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6030,3,18,125,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6031,3,18,124,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6032,3,18,114,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6033,3,18,102,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6034,3,18,90,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6035,3,18,78,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6036,3,18,66,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6037,3,18,55,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6038,3,17,150,10,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6039,3,17,147,10,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6040,3,17,143,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6041,3,17,141,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6042,3,17,136,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6043,3,17,132,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6044,3,17,128,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6045,3,17,123,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6046,3,17,117,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6047,3,17,116,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6048,3,17,115,7,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6049,3,17,114,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6050,3,17,105,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6051,3,17,95,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6052,3,17,87,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6053,3,17,78,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6054,3,17,69,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6055,3,17,60,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6056,3,16,150,9,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6057,3,16,149,9,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6058,3,16,148,9,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6059,3,16,147,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6060,3,16,142,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6061,3,16,138,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6062,3,16,136,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6063,3,16,129,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6064,3,16,128,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6065,3,16,127,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6066,3,16,126,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6067,3,16,125,7,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6068,3,16,124,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6069,3,16,116,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6070,3,16,105,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6071,3,16,94,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6072,3,16,83,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6073,3,16,72,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6074,3,16,61,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6075,3,16,50,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6076,3,15,150,9,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6077,3,15,149,9,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6078,3,15,146,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6079,3,15,140,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6080,3,15,139,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6081,3,15,132,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6082,3,15,128,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6083,3,15,127,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6084,3,15,126,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6085,3,15,125,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6086,3,15,124,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6087,3,15,123,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6088,3,15,122,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6089,3,15,121,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6090,3,15,120,7,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6091,3,15,119,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6092,3,15,118,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6093,3,15,107,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6094,3,15,97,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6095,3,15,86,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6096,3,15,76,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6097,3,15,65,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6098,3,15,55,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6099,3,14,150,12,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6100,3,14,148,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6101,3,14,144,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6102,3,14,142,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6103,3,14,135,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6104,3,14,127,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6105,3,14,121,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6106,3,14,120,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6107,3,14,119,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6108,3,14,118,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6109,3,14,117,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6110,3,14,116,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6111,3,14,115,8,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6112,3,14,114,8);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6113,3,14,112,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6114,3,14,105,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6115,3,14,97,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6116,3,14,90,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6117,3,14,82,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6118,3,14,75,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6119,3,14,67,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6120,3,14,60,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6121,3,13,150,12,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6122,3,13,146,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6123,3,13,142,11,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6124,3,13,140,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6125,3,13,135,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6126,3,13,130,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6127,3,13,128,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6128,3,13,121,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6129,3,13,119,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6130,3,13,114,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6131,3,13,113,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6132,3,13,112,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6133,3,13,111,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6134,3,13,110,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6135,3,13,109,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6136,3,13,108,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6137,3,13,107,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6138,3,13,106,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6139,3,13,105,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6140,3,13,104,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6141,3,13,100,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6142,3,13,93,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6143,3,13,86,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6144,3,13,79,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6145,3,13,72,1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6146,3,13,65,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6147,3,12,150,8,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6148,3,12,147,8,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6149,3,12,143,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6150,3,12,137,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6151,3,12,133,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6152,3,12,126,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6153,3,12,125,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6154,3,12,124,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6155,3,12,123,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6156,3,12,122,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6157,3,12,121,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6158,3,12,120,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6159,3,12,119,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6160,3,12,118,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6161,3,12,117,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6162,3,12,116,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6163,3,12,115,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6164,3,12,114,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6165,3,12,113,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6166,3,12,112,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6167,3,12,111,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6168,3,12,110,5,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6169,3,12,109,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6170,3,12,101,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6171,3,12,89,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6172,3,12,77,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6173,3,12,65,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6174,3,11,150,10,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6175,3,11,145,10,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6176,3,11,141,9,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6177,3,11,140,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6178,3,11,133,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6179,3,11,129,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6180,3,11,125,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6181,3,11,123,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6182,3,11,122,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6183,3,11,121,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6184,3,11,120,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6185,3,11,119,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6186,3,11,118,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6187,3,11,117,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6188,3,11,116,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6189,3,11,115,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6190,3,11,114,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6191,3,11,113,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6192,3,11,112,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6193,3,11,111,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6194,3,11,110,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6195,3,11,109,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6196,3,11,108,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6197,3,11,107,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6198,3,11,106,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6199,3,11,105,5,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6200,3,11,104,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6201,3,11,100,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6202,3,11,91,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6203,3,11,83,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6204,3,11,75,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6205,3,10,150,14,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6206,3,10,145,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6207,3,10,143,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6208,3,10,138,13,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6209,3,10,137,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6210,3,10,131,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6211,3,10,125,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6212,3,10,120,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6213,3,10,119,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6214,3,10,118,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6215,3,10,117,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6216,3,10,116,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6217,3,10,115,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6218,3,10,114,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6219,3,10,113,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6220,3,10,112,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6221,3,10,111,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6222,3,10,110,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6223,3,10,109,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6224,3,10,108,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6225,3,10,107,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6226,3,10,106,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6227,3,10,105,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6228,3,10,104,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6229,3,10,103,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6230,3,10,102,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6231,3,10,101,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6232,3,10,100,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6233,3,10,99,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6234,3,10,94,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6235,3,10,88,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6236,3,10,82,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6237,3,10,76,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6238,3,10,70,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6239,3,9,150,14,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6240,3,9,144,13,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6241,3,9,142,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6242,3,9,138,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6243,3,9,133,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6244,3,9,132,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6245,3,9,126,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6246,3,9,121,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6247,3,9,118,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6248,3,9,115,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6249,3,9,114,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6250,3,9,113,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6251,3,9,112,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6252,3,9,111,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6253,3,9,110,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6254,3,9,109,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6255,3,9,108,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6256,3,9,107,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6257,3,9,106,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6258,3,9,105,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6259,3,9,104,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6260,3,9,103,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6261,3,9,102,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6262,3,9,101,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6263,3,9,100,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6264,3,9,99,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6265,3,9,98,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6266,3,9,97,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6267,3,9,96,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6268,3,9,95,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6269,3,9,94,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6270,3,9,93,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6271,3,9,92,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6272,3,9,91,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6273,3,9,90,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6274,3,9,89,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6275,3,9,86,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6276,3,9,80,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6277,3,9,75,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6278,3,8,150,10,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6279,3,8,143,10,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6280,3,8,138,9,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6281,3,8,136,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6282,3,8,126,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6283,3,8,122,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6284,3,8,121,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6285,3,8,120,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6286,3,8,119,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6287,3,8,118,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6288,3,8,117,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6289,3,8,116,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6290,3,8,115,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6291,3,8,114,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6292,3,8,113,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6293,3,8,112,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6294,3,8,111,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6295,3,8,110,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6296,3,8,109,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6297,3,8,108,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6298,3,8,107,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6299,3,8,106,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6300,3,8,105,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6301,3,8,104,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6302,3,8,103,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6303,3,8,102,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6304,3,8,101,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6305,3,8,100,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6306,3,8,99,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6307,3,8,98,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6308,3,8,97,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6309,3,8,96,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6310,3,8,95,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6311,3,8,94,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6312,3,8,93,6,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6313,3,8,92,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6314,3,8,90,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6315,3,8,78,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6316,3,8,66,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6317,3,8,55,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6318,3,7,150,10,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6319,3,7,141,10,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6320,3,7,138,9,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6321,3,7,130,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6322,3,7,127,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6323,3,7,118,8,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6324,3,7,117,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6325,3,7,116,7,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6326,3,7,115,7,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6327,3,7,114,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6328,3,7,113,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6329,3,7,112,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6330,3,7,111,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6331,3,7,110,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6332,3,7,109,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6333,3,7,108,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6334,3,7,107,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6335,3,7,106,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6336,3,7,105,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6337,3,7,104,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6338,3,7,103,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6339,3,7,102,6,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6340,3,7,101,6,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6341,3,7,100,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6342,3,7,99,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6343,3,7,98,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6344,3,7,97,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6345,3,7,96,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6346,3,7,95,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6347,3,7,94,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6348,3,7,93,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6349,3,7,92,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6350,3,7,91,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6351,3,7,90,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6352,3,7,89,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6353,3,7,88,5,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6354,3,7,87,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6355,3,7,82,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6356,3,7,71,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6357,3,7,60,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6358,3,6,150,15,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6359,3,6,143,14,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6360,3,6,140,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6361,3,6,136,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6362,3,6,130,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6363,3,6,129,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6364,3,6,123,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6365,3,6,117,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6366,3,6,116,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6367,3,6,115,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6368,3,6,114,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6369,3,6,113,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6370,3,6,112,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6371,3,6,111,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6372,3,6,110,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6373,3,6,109,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6374,3,6,108,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6375,3,6,107,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6376,3,6,106,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6377,3,6,105,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6378,3,6,104,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6379,3,6,103,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6380,3,6,102,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6381,3,6,101,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6382,3,6,100,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6383,3,6,99,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6384,3,6,98,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6385,3,6,97,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6386,3,6,96,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6387,3,6,95,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6388,3,6,94,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6389,3,6,93,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6390,3,6,92,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6391,3,6,91,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6392,3,6,90,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6393,3,6,89,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6394,3,6,88,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6395,3,6,87,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6396,3,6,86,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6397,3,6,85,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6398,3,6,84,5,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6399,3,6,83,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6400,3,6,82,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6401,3,6,78,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6402,3,6,71,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6403,3,6,65,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6404,3,5,150,18,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6405,3,5,145,17,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6406,3,5,140,16,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6407,3,5,138,16,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6408,3,5,135,15,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6409,3,5,130,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6410,3,5,125,13,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6411,3,5,120,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6412,3,5,115,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6413,3,5,114,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6414,3,5,113,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6415,3,5,112,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6416,3,5,111,11,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6417,3,5,110,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6418,3,5,109,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6419,3,5,108,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6420,3,5,107,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6421,3,5,106,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6422,3,5,105,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6423,3,5,104,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6424,3,5,103,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6425,3,5,102,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6426,3,5,101,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6427,3,5,100,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6428,3,5,99,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6429,3,5,98,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6430,3,5,97,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6431,3,5,96,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6432,3,5,95,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6433,3,5,94,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6434,3,5,93,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6435,3,5,92,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6436,3,5,91,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6437,3,5,90,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6438,3,5,89,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6439,3,5,88,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6440,3,5,87,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6441,3,5,86,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6442,3,5,85,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6443,3,5,84,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6444,3,5,83,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6445,3,5,82,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6446,3,5,81,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6447,3,5,80,4,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6448,3,5,79,4,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6449,3,5,78,4,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6450,3,5,77,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6451,3,5,75,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6452,3,5,70,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6453,3,4,150,12,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6454,3,4,143,11,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6455,3,4,140,11,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6456,3,4,137,10,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6457,3,4,132,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6458,3,4,131,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6459,3,4,130,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6460,3,4,129,9,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6461,3,4,128,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6462,3,4,127,9,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6463,3,4,126,9,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6464,3,4,125,9,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6465,3,4,124,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6466,3,4,123,8,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6467,3,4,122,8,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6468,3,4,121,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6469,3,4,120,8,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6470,3,4,119,8,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6471,3,4,118,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6472,3,4,117,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6473,3,4,116,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6474,3,4,115,7,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6475,3,4,114,7,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6476,3,4,113,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6477,3,4,112,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6478,3,4,111,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6479,3,4,110,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6480,3,4,109,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6481,3,4,108,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6482,3,4,107,6,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6483,3,4,106,6,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6484,3,4,105,5,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6485,3,4,104,5,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6486,3,4,103,5,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6487,3,4,102,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6488,3,4,99,4);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6489,3,4,92,3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6490,3,4,86,2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6491,3,4,80,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6492,3,3,150,15,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6493,3,3,144,14,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6494,3,3,140,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6495,3,3,139,14,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6496,3,3,138,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6497,3,3,132,12,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6498,3,3,128,12,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6499,3,3,127,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6500,3,3,126,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6501,3,3,125,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6502,3,3,124,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6503,3,3,123,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6504,3,3,122,11,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6505,3,3,121,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6506,3,3,120,10,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6507,3,3,119,10,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6508,3,3,118,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6509,3,3,117,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6510,3,3,116,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6511,3,3,115,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6512,3,3,114,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6513,3,3,113,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6514,3,3,112,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6515,3,3,111,9,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6516,3,3,110,9,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6517,3,3,109,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6518,3,3,108,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6519,3,3,107,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6520,3,3,106,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6521,3,3,105,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6522,3,3,104,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6523,3,3,103,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6524,3,3,102,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6525,3,3,101,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6526,3,3,100,7,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6527,3,3,99,7,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6528,3,3,98,7,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6529,3,3,97,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6530,3,3,96,6);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6531,3,3,90,5);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6532,3,3,85,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6533,3,2,150,18,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6534,3,2,143,17,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6535,3,2,137,16,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6536,3,2,131,15,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6537,3,2,130,15,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6538,3,2,125,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6539,3,2,121,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6540,3,2,120,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6541,3,2,119,14,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6542,3,2,118,13,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6543,3,2,117,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6544,3,2,116,13,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6545,3,2,115,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6546,3,2,114,13,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6547,3,2,113,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6548,3,2,112,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6549,3,2,111,12,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6550,3,2,110,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6551,3,2,109,12,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6552,3,2,108,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6553,3,2,107,12,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6554,3,2,106,11,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6555,3,2,105,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6556,3,2,104,11,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6557,3,2,103,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6558,3,2,102,11,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6559,3,2,101,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6560,3,2,100,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6561,3,2,99,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6562,3,2,98,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6563,3,2,97,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6564,3,2,96,10,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6565,3,2,95,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6566,3,2,94,10,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6567,3,2,93,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6568,3,2,92,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6569,3,2,91,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6570,3,2,90,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6571,3,2,89,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6572,3,2,88,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6573,3,2,87,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6574,3,2,86,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6575,3,2,85,8,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6576,3,2,84,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6577,3,2,83,8,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6578,3,2,82,8);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6579,3,2,81,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6580,3,2,75,0);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6581,3,1,150,20,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6582,3,1,145,19,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6583,3,1,140,18,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6584,3,1,136,17,'E',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6585,3,1,133,17,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6586,3,1,131,16,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6587,3,1,127,16,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6588,3,1,126,15,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6589,3,1,125,15,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6590,3,1,124,15,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6591,3,1,123,15,'D',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6592,3,1,122,14,'D',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6593,3,1,121,14,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6594,3,1,120,14,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6595,3,1,119,14,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6596,3,1,118,14,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6597,3,1,117,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6598,3,1,116,13,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6599,3,1,115,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6600,3,1,114,13,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6601,3,1,113,13,'C',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6602,3,1,112,12,'C',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6603,3,1,111,12,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6604,3,1,110,12,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6605,3,1,109,12,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6606,3,1,108,11,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6607,3,1,107,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6608,3,1,106,11,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6609,3,1,105,11,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6610,3,1,104,11,'B',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6611,3,1,103,10,'B',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6612,3,1,102,10,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6613,3,1,101,10,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6614,3,1,100,10,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6615,3,1,99,10,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6616,3,1,98,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6617,3,1,97,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6618,3,1,96,9,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6619,3,1,95,9,'A',1);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6620,3,1,94,8,'A',2);
insert into AttackTableEntry(id, weapon_id, at, roll, hits, crit_severity, criticalTable_id) values(6621,3,1,93,8,'A',3);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6622,3,1,92,8);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6623,3,1,89,7);
insert into AttackTableEntry(id, weapon_id, at, roll, hits) values(6624,3,1,85,0);
